# Generated by Django 4.2.17 on 2025-01-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('Hiking', 'Hiking'), ('Mud Run', 'Mud Run'), ('Other', 'Other')], default='Other', max_length=20)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('organisator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='outdoorevents.organisator')),
            ],
        ),
    ]
