# Generated by Django 4.2.17 on 2025-01-22 11:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorevents', '0002_organisator_contact_info_organisator_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisator',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
